"""Initial migration

Revision ID: d91698f20065
Revises: 
Create Date: 2025-03-04 20:29:33.364000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd91698f20065'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Сначала удаляем таблицы с зависимостями
    op.execute("DROP TABLE IF EXISTS bookings CASCADE")
    op.execute("DROP TABLE IF EXISTS rooms CASCADE")
    op.execute("DROP TABLE IF EXISTS hotels CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    
    # Затем создаем новые таблицы
    op.create_table('networks',
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('network_name', sa.String(), nullable=False),
    sa.Column('network_type', sa.String(), nullable=False),
    sa.Column('network_url', sa.String(), nullable=False),
    sa.Column('network_currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('network_id')
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token_name', sa.String(), nullable=False),
    sa.Column('token_symbol', sa.String(), nullable=False),
    sa.Column('token_decimals', sa.Integer(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('token_network_id', sa.Integer(), nullable=False),
    sa.Column('staking_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['token_network_id'], ['networks.network_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('wallets',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('wallet_type', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.network_id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_table('staking',
    sa.Column('staking_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('staked_at', sa.Date(), nullable=False),
    sa.Column('unstaked_at', sa.Date(), nullable=True),
    sa.Column('staking_type', sa.String(), nullable=False),
    sa.Column('staking_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.token_id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.wallet_id'], ),
    sa.PrimaryKeyConstraint('staking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_days', sa.INTEGER(), sa.Computed('(date_to - date_from)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.INTEGER(), sa.Computed('((date_to - date_from) * price)', persisted=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='bookings_room_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='bookings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bookings_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_pass', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_table('hotels',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('hotels_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('services', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rooms_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hotels_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('rooms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('services', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='rooms_hotel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rooms_pkey')
    )
    op.drop_table('staking')
    op.drop_table('wallets')
    op.drop_table('tokens')
    op.drop_table('networks')
    # ### end Alembic commands ###
